### ISSUE TITLE
present一个组件后，退出时执行[self dismissViewAction]奔溃

### ISSUE THREAD

**Issue by iT-Boyer** [yizzuide/XFLegoVIPER#10]
[config enableLog];开启打印日志时，当退出组件时执行打印组件跟踪路径导致崩溃：
```
__kindof id<XFComponentRoutable> component = [__componentTable objectForKey:__componentKeyArr[0]];
```
`__componentKeyArr`此时空数组，索引越界导致崩溃。
>Thread 1: "*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array"

**Comment by iT-Boyer** [comment]
暂时处理方式，关闭日志功能：//[config enableLog];

**Comment by iT-Boyer** [comment]
@yizzuide 这里有个崩溃，暂时只能关闭日志解决。

**Comment by yizzuide** [comment]
更新版本到 4.20.1
