### ISSUE TITLE
there is a crash when enablelog is on

### ISSUE THREAD

**Issue by ohmyDavie** [yizzuide/XFLegoVIPER#6]
use  XF_ShowURLComponent2Window_Fast(@"XXXX") to change rootWindow and if page from "start" to "main" that's all right but if page form "start" to "login" and then into "main" there was a crash when enableLog is on.

then  i find this:
NSMapTable {
[7] Login -> <ZRLoginPresenter: 0x600000115c30>
[12] IndexTab -> <ZRIndexTabPresenter: 0x6000000b33e0>
}

<__NSArrayM 0x60400025fef0>(
Start,
Login,
IndexTab
)

it causes  component  became nil in below codes.

XFComponentManager.m

 __kindof id<XFComponentRoutable> component = [__componentTable objectForKey:__componentKeyArr[0]];
        [self _printComponentTree:component logStr:logStrM];

so why did it happen? and how to make it work correctly?
when i close enablelog  all things is ok.

**Comment by yizzuide** [comment]
do you find __componentKeyArr[0] is nil or [self _printComponentTree:component logStr:logStrM] has nil?
