### ISSUE TITLE
[XFURLRoute enableVerifyURLRoute]; 方法无效

### ISSUE THREAD

**Issue by iT-Boyer** [yizzuide/XFLegoVIPER#9]

**Comment by yizzuide** [comment]
XFURLRoute这个类没有这个方法啊

**Comment by iT-Boyer** [comment]
嗯，是优化掉了吗。有类似的方法来查看有效的组件URL吗？

**Comment by iT-Boyer** [comment]
基于mvc的旧项目，想要跳转到乐高组件中，必须把mvc中的Viewcontroller控制器导出组件才行吗？
如果不通过Viewcontroller，而是通过继承NSObject的接口类，该如何在NSObject类中封装跳转组件的方法呢？

**Comment by yizzuide** [comment]
关于旧项目的控制器跳转乐高组件可查看 #4

**Comment by yizzuide** [comment]
验证组件是否可用，可通过打开组件[XFURLRoute open:transitionBlock:]这方法返回值来判定，返回NO表示组件不存在

**Comment by iT-Boyer** [comment]
嗯，非常谢谢，我尝试下
